config/routes.rb
Rails.application.routes.draw do
  get 'adlog', to: 'admlog#log'
  delete 'logout', to: 'admlog#destroy'
  post 'adlog', to: 'admlog#dosome'
  root 'posts#index'
  get 'create_post', to: 'posts#create'
  post 'create_post', to: 'posts#new'
  delete 'delete/:id', to: 'posts#delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin
  has_one_attached :image
end

app/controllers/admlog_controller.rb
class AdmlogController < ApplicationController
  def log
    redirect_to root_url if isadm
  end
  def logout
  end
  def dosome
    adm = Admin.find_by(email: params[:session][:email].downcase)
    if adm && adm.authenticate(params[:session][:password])
      log_in adm
      redirect_to root_url 
    else
      redirect_to root_url
    end
  end
  def destroy 
    session.delete(:adm_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :isadmin, only: [:create, :new, :delete]
  def index
    @posts = Post.all.reverse
  end
  def create
  end
  def new
    post = curadm.posts.create(post_params)
    if post.save
      redirect_to root_url
    else
      redirect_to post_create_url
    end
  end
  def delete
    curadm.posts.find(params[:id]).delete
    redirect_to root_url
  end
  private
  def post_params
    params.require(:post).permit(:title, :content, :image)
  end
  def isadmin
    if !isadm
      redirect_to root_url and return
    end
  end
end

app/helpers/admlog_helper.rb
module AdmlogHelper
  def log_in(adm)
    session[:adm_id] = adm.id
  end
  def isadm
    session[:adm_id] != nil
  end
  def curadm
    Admin.find(session[:adm_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def log_in(adm)
    session[:adm_id] = adm.id
  end
  def isadm
    session[:adm_id] != nil
  end
  def curadm
    Admin.find(session[:adm_id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admlog/log.html.erb
<% provide(:title, "Пшел вон") %>
<h1 align="center">LGADM</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: adlog_url) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('nibirusmall.png') %>
  </head>

  <body>
    <%= image_tag "nibiru.png", alt: "log", class: 'logo' %>
      <% if isadm %>
          <%= link_to (image_tag "exit.svg"), logout_path, method: :delete, class: "float" %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<% provide(:title, "New post") %>
<h1>New post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:post, url: create_post_url) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>

      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Лента") %>
<% if isadm %>
  <%= link_to image_tag("add.svg"), create_post_url, class: "float1" %>
<% end %>
<% if @posts.any? %>
  <% @posts.each do |post| %>
  <div id="post">
    <h1 align="center"><%= post.title %></h1>
    <p><%= post.content %></p>
    <% if post.image.attached? %>
      <img src="<%= url_for(post.image) %>"></img>
    <% end %>
    <% if isadm %>
      <%= link_to 'delete', '/delete/' + post.id.to_s, method: :delete %>   
    <% end %>
    </div>
  <% end %>
<% end %>